workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
    artifacts:
      - build/**
